### PR TITLE
Issue 43 - Models for quiz app

### PR DESCRIPTION
**Pull request by DurianZealot**
#43

### CODE REVIEW

**Comment by DurianZealot** [comment]
File changes that happen in solving issue #41 also show up in this PR. 

I am still confused about how to use `git rebase` to avoid this redundancy in `Files changed`. 

[An online tutorial](https://www.youtube.com/watch?v=CRlGDDprdOQ) gives example that `git rebase` is used in situations like the following: 
```
master has commits  1 - 2 - 3
                        |
feature has commits     2 -  4 
```
and then `rebase` `feature` to `master` will make `master` has commits ` 1 - 2 - 3 - 4 `. I don't see it has anything to deal with the issue of showing duplicate changed files here :(

**Comment by Windsooon** [comment]
This PR should create after PR #42 has been merged.

**Comment by DurianZealot** [comment]
I will add a more detailed model to record answers for each question from users soon.

**Comment by Windsooon** [comment]
One PR just for one or two commits and fewer file changes. @DurianZealot

**Pull request closed without merging**
